"""商品名称英译中翻译引擎 v2 — 基于UCI Online Retail数据集完整词库"""

import re

COLORS = {
    "RED": "红色", "BLUE": "蓝色", "GREEN": "绿色", "PINK": "粉色",
    "WHITE": "白色", "BLACK": "黑色", "YELLOW": "黄色", "PURPLE": "紫色",
    "ORANGE": "橙色", "GREY": "灰色", "GOLD": "金色", "SILVER": "银色",
    "BROWN": "棕色", "CREAM": "奶油色", "IVORY": "象牙白", "NATURAL": "自然色",
    "CLEAR": "透明", "MIXED": "混色", "MULTI": "多彩", "LIME": "青柠色",
    "TURQUOISE": "绿松石色", "LILAC": "淡紫色", "PEACH": "桃色",
    "NAVY": "藏青色", "BEIGE": "米色", "CORAL": "珊瑚色",
}

MATERIALS = {
    "WOODEN": "木质", "CERAMIC": "陶瓷", "GLASS": "玻璃", "METAL": "金属",
    "FELT": "毛毡", "FELTCRAFT": "毛毡手工", "ENAMEL": "珐琅",
    "ZINC": "锌合金", "CRYSTAL": "水晶", "ACRYLIC": "亚克力",
    "WOOL": "羊毛", "WOOLLY": "羊毛", "SILK": "丝绸", "LINEN": "亚麻布",
    "WICKER": "藤编", "LEATHER": "皮革", "CANVAS": "帆布",
    "CHROME": "铬色", "BRASS": "黄铜", "COPPER": "铜",
    "PLASTIC": "塑料", "RUBBER": "橡胶", "FOAM": "泡沫",
    "PADDED": "填充", "SOFT": "柔软", "FLAT": "扁平",
    "PAINTED": "彩绘", "HANDMADE": "手工制作", "HAND": "手工",
}

STYLES = {
    "VINTAGE": "复古", "RETRO": "怀旧", "RETROSPOT": "复古圆点",
    "ANTIQUE": "古董风", "CLASSIC": "经典", "MODERN": "现代",
    "BAROQUE": "巴洛克", "ART": "艺术", "FRENCH": "法式",
    "ENGLISH": "英伦", "COUNTRY": "乡村", "COTTAGE": "小屋",
    "FOLKART": "民间艺术", "BOHEMIAN": "波西米亚",
    "SHABBY": "做旧", "CHIC": "别致", "GLAM": "华丽",
    "MINIMAL": "简约", "RUSTIC": "乡村风", "INDUSTRIAL": "工业风",
    "FANCY": "花式", "FANCYFONT": "艺术字体", "STRIPED": "条纹",
    "STRIPE": "条纹", "STRIPES": "条纹", "GINGHAM": "格纹",
    "POLKA DOT": "波点", "POLKADOT": "波点", "SPOTTY": "圆点",
    "SPOT": "圆点", "SPOTS": "圆点", "DOT": "点",
    "CHECK": "格子", "PLAID": "格子", "TARTAN": "苏格兰格",
    "FLORAL": "花卉", "BOTANICAL": "植物", "DAISY": "雏菊",
    "PAISLEY": "佩斯利花纹", "FILIGREE": "金银丝", "FLOCK": "植绒",
    "LACE": "蕾丝", "RUFFLED": "荷叶边", "FRILLED": "褶边",
    "EMBOSSED": "浮雕", "PRINTED": "印花", "PLAIN": "素色",
    "DIAMANTE": "水钻", "BLING": "闪亮", "GLITTER": "闪光",
    "SEQUIN": "亮片", "BEADED": "珠饰",
}

PRODUCTS_CORE = {
    "HOT WATER BOTTLE": "热水袋", "WATER BOTTLE": "水壶",
    "COFFEE CUP": "咖啡杯", "TEA CUP": "茶杯", "TEA MUG": "茶杯",
    "COFFEE MUG": "咖啡杯", "MUG": "马克杯", "TEACUP": "茶杯",
    "SAUCER": "杯碟", "CUP": "杯子", "PLATE": "盘子",
    "BOWL": "碗", "DISH": "碟子", "JAR": "罐子",
    "BOTTLE": "瓶子", "BOX": "盒子", "TIN": "铁罐", "TINS": "铁罐",
    "BAG": "包", "PURSE": "钱包", "POUCH": "小包", "WALLET": "钱包",
    "BASKET": "篮子", "CASE": "箱子", "CASES": "箱套",
    "STORAGE BOX": "收纳盒", "TRINKET BOX": "饰品盒",
    "TRINKET POT": "饰品罐", "MONEY BOX": "存钱罐",
    "TISSUE BOX": "纸巾盒", "TOASTER COVER": "烤面包机罩",
    "LUNCH BAG": "午餐包", "LUNCH BOX": "饭盒", "LUNCHBOX": "饭盒",
    "CAKE TIN": "蛋糕模具", "CAKE STAND": "蛋糕架",
    "BAKING SET": "烘焙套装", "BAKING MOULD": "烘焙模具",
    "NAPKINS": "餐巾", "PAPER NAPKINS": "纸巾",
    "PAPER CUPS": "纸杯", "PAPER CRAFT": "纸艺品",
    "CHALK STICKS": "粉笔", "PENCILS": "铅笔", "PEN": "笔",
    "NOTEBOOK": "笔记本", "WRITING SET": "文具套装",
    "MEASURING SPOONS": "量勺", "MEASURING SPOON": "量勺",
    "NIGHT LIGHT": "小夜灯", "LED NIGHT LIGHT": "LED小夜灯",
    "LIGHTS": "灯串", "LIGHT": "灯", "LANTERN": "灯笼",
    "CANDLE": "蜡烛", "CANDLES": "蜡烛", "TEALIGHT": "茶蜡",
    "T-LIGHT": "茶蜡", "HOLDER": "烛台", "CANDLE IN TIN": "罐装蜡烛",
    "INCENSE": "香薰", "SCENTED": "香氛",
    "DOOR MAT": "门垫", "DOORMAT": "门垫", "MAT": "垫子",
    "COASTER SET": "杯垫套装", "COASTER": "杯垫", "COASTERS": "杯垫",
    "CUSHION": "靠垫", "PILLOW": "枕头", "THROW": "盖毯",
    "TOWEL": "毛巾", "APRON": "围裙",
    "FRAME": "相框", "RECORD FRAME": "唱片相框", "PHOTO FRAME": "相框",
    "PICTURE": "画", "POSTER": "海报",
    "CLOCK": "钟表", "WALL CLOCK": "挂钟", "ALARM": "闹钟",
    "MIRROR": "镜子",
    "NECKLACE": "项链", "BRACELET": "手链", "EARRINGS": "耳环",
    "RING": "戒指", "CHARM": "吊坠", "BANGLE": "手镯",
    "BROOCH": "胸针", "JEWELLERY": "首饰",
    "KEY CHAIN": "钥匙扣", "KEY RING": "钥匙圈", "KEY": "钥匙",
    "MOBILE PHONE CHARM": "手机挂饰", "PHONE CHARM": "手机链",
    "HAIR GRIP": "发夹", "HAIR BAND": "发带", "HAIR CLIP": "发夹",
    "HEADBAND": "发箍", "COMB": "梳子",
    "CARD": "卡片", "GREETING CARD": "贺卡", "BIRTHDAY CARD": "生日贺卡",
    "GIFT TAGS": "礼物标签", "GIFT TAG": "礼物签",
    "GIFT WRAP": "礼品包装", "WRAP": "包装纸",
    "GIFT": "礼品", "PRESENT": "礼物",
    "MAGNET": "磁铁", "MAGNETS": "磁贴", "FRIDGE MAGNET": "冰箱贴",
    "FRIDGE MAGNETS": "冰箱贴",
    "STICKER": "贴纸", "STICKERS": "贴纸", "STICKER SET": "贴纸套装",
    "DECORATION": "装饰", "DECORATIONS": "装饰",
    "ORNAMENT": "装饰品", "ORNAMENTS": "装饰品",
    "HANGING": "挂饰", "MOBILE": "挂饰", "BUNTING": "彩旗",
    "BANNER": "横幅", "FLAG": "旗帜", "WREATH": "花环",
    "GARLAND": "花环", "TREE": "树", "CHRISTMAS TREE": "圣诞树",
    "STOCKING": "圣诞袜",
    "SIGN": "标牌", "METAL SIGN": "金属标牌", "PLAQUE": "牌匾",
    "DOORSIGN": "门牌", "DOOR SIGN": "门牌",
    "TAPE": "胶带", "BARRIER TAPE": "警戒带", "CORDON": "警戒线",
    "HOOK": "挂钩", "KNOB": "旋钮", "HANDLE": "把手",
    "DRAWER": "抽屉", "CABINET": "柜子", "CHEST": "箱柜",
    "SHELF": "架子", "STAND": "支架", "BASE": "底座",
    "TRAY": "托盘", "PLATTER": "大托盘", "DISHES": "餐具套装",
    "TABLE": "桌子", "TABLEWARE": "餐具", "CUTLERY": "刀叉餐具",
    "COVER": "罩", "CASE": "套",
    "DOLL": "玩偶", "TEDDY": "泰迪熊", "FIGURE": "人偶",
    "TOY": "玩具", "GAME": "游戏", "PUZZLE": "拼图",
    "BUILDING BLOCK": "积木", "BLOCK LETTERS": "积木字母",
    "WOOD LETTERS": "木字母", "NUMBER": "数字",
    "SNAP CARDS": "配对卡牌", "JIGSAW": "拼图",
    "RUSSIAN DOLL": "套娃", "SCOTTIE DOG": "苏格兰梗犬",
    "MONKEY DOLL": "猴子玩偶", "BUNNY": "兔子", "RABBIT": "兔子",
    "DOG": "狗", "CAT": "猫", "BIRD": "鸟", "DUCK": "鸭子",
    "DUCKS": "鸭子", "FLYING DUCKS": "飞鸭", "DOVE": "鸽子",
    "BUTTERFLY": "蝴蝶", "HEART": "爱心", "STAR": "星星",
    "FLOWER": "花", "FLOWERS": "花束", "ROSE": "玫瑰",
    "BOWL": "碗", "EGG": "蛋", "EGGS": "鸡蛋",
    "BISCUIT": "饼干", "BISCUITS": "饼干", "CAKE": "蛋糕",
    "CAKES": "蛋糕", "MUFFIN": "玛芬", "DOUGHNUT": "甜甜圈",
    "MARSHMALLOWS": "棉花糖", "CANDY": "糖果", "SWEET": "糖果",
    "SWEETS": "糖果", "JAM": "果酱", "HONEY": "蜂蜜",
    "TEA": "茶", "COFFEE": "咖啡", "CHOCOLATE": "巧克力",
    "GIN": "金酒", "TONIC": "汤力水", "WINE": "葡萄酒",
    "KITCHEN": "厨房", "GARDEN": "花园", "HOME": "家",
    "BATH": "浴室", "PARTY": "派对", "CHRISTMAS": "圣诞",
    "EASTER": "复活节", "BIRTHDAY": "生日",
    "WASTEPAPER BIN": "废纸篓", "BIN": "垃圾桶",
    "UMBRELLA": "雨伞", "PARASOL": "遮阳伞",
    "SHOPPER": "购物袋", "TOTE": "托特包", "SATCHEL": "挎包",
    "BACKPACK": "双肩包", "RUCKSACK": "背包",
    "PANTRY": "食品储藏室", "TUBE": "筒装", "CANISTER": "储物罐",
    "CONTAINER": "容器", "FOOD CONTAINER": "食品盒",
    "WARMER": "保温套", "EGG WARMER": "蛋托保温套",
    "CIGAR": "雪茄", "CIGAR BOX": "雪茄盒",
    "SOAP": "肥皂", "SOAP DISH": "肥皂碟",
    "FLASK": "保温瓶", "THERMOS": "保温杯",
    "THERMOMETER": "温度计",
    "SCISSORS": "剪刀", "KNIFE": "刀具", "SPOON": "勺子",
    "FORK": "叉子", "LADLE": "长柄勺", "SPOON REST": "勺子托",
    "SCALES": "秤", "KITCHEN SCALES": "厨房秤",
    "WIRE": "铁丝", "ORGANISER": "收纳架", "ORGANIZER": "收纳架",
    "KITCHEN ORGANISER": "厨房收纳架", "KITCHEN ORGANIZER": "厨房收纳架",
    "PLAYHOUSE": "玩具屋", "PLAY KITCHEN": "玩具厨房",
    "MOTHER'S": "妈妈的", "MOTHERS": "妈妈",
    "POPPY'S": "波比的", "POPPYS": "波比",
    "MINT": "薄荷绿",
    "BUTTONS": "纽扣", "THREAD": "线轴", "REEL": "线轴",
    "BEADS": "珠子", "BEAD": "珠子", "PEARL": "珍珠",
    "SHELL": "贝壳", "STONE": "石头", "PEBBLE": "鹅卵石",
    "FEATHER": "羽毛", "LEAF": "叶子", "LEAVES": "树叶",
    "PINECONE": "松果", "ACORN": "橡果",
    "APPLE": "苹果", "CHERRY": "樱桃", "STRAWBERRY": "草莓",
    "LEMON": "柠檬", "ORANGE FRUIT": "橙子",
    "CARROT": "胡萝卜", "TOMATO": "番茄",
    "LAVENDER": "薰衣草", "CINNAMON": "肉桂",
    "VANILLA": "香草", "EUCALYPTUS": "桉树",
    "SKULL": "骷髅", "DINOSAUR": "恐龙",
    "GLOBE": "地球仪", "POLITICAL GLOBE": "地球仪",
    "UNION JACK": "米字旗", "UNION JACK FLAG": "英国国旗",
    "BILLBOARD": "广告牌",
    "DINER": "餐厅", "BAKERY": "面包店",
    "CHILDRENS": "儿童款", "KIDS": "儿童",
    "GIRLS": "女孩", "BOYS": "男孩", "GIRL": "女孩",
    "BABY": "婴儿", "INFANT": "婴幼儿",
    "SMALL": "小型", "LARGE": "大型", "GIANT": "巨型",
    "JUMBO": "特大号", "MINI": "迷你", "MICRO": "微型",
    "ROUND": "圆形", "SQUARE": "方形", "OVAL": "椭圆形",
    "TALL": "高型", "SHORT": "矮型", "LONG": "长型",
    "DEEP": "深型", "SHALLOW": "浅型",
    "SET": "套装", "PACK": "件装", "KIT": "工具包",
    "ASSORTED": "多色", "MIX": "混合", "VARIETY": "多样",
    "COLLECTION": "系列", "RANGE": "系列",
    "SINGLE": "单件", "DOUBLE": "双层", "TRIPLE": "三层",
    "PAIR": "一对", "TWIN": "双胞胎",
    "FOLDING": "可折叠", "STACKABLE": "可叠放",
    "REUSABLE": "可重复使用", "DISPOSABLE": "一次性",
    "PERSONALISED": "个性化", "CUSTOM": "定制",
    "DELUXE": "豪华版", "PREMIUM": "高级",
    "ORIGINAL": "原版", "NEW": "新款",
    "CLASSIC": "经典", "LIMITED": "限量",
    "EXTRA": "加厚", "PLUS": "加大",
    "CM": "厘米", "INCH": "英寸", "SIZE": "尺寸",
    "PC": "件", "PICE": "件",
    "ON": "开", "OFF": "关",
    "SWEETHEART": "甜心", "LOVE": "爱", "JOY": "欢乐",
    "PEACE": "和平", "HOPE": "希望", "DREAM": "梦想",
    "LUCKY": "幸运", "BEST": "最佳", "HAPPY": "快乐",
    "FRIEND": "朋友", "FAMILY": "家庭", "MUM": "妈妈",
    "DAD": "爸爸", "GRAN": "奶奶", "GRANDMA": "外婆",
    "SISTER": "姐妹", "BROTHER": "兄弟",
    "HOME SWEET HOME": "甜蜜之家",
    "SAVE THE PLANET": "拯救地球",
    "PLEASE ONE PERSON": "限一人",
    "AREA PATROLLED": "区域巡逻",
    "FULL ENGLISH BREAKFAST": "英式全早餐",
    "RED TOADSTOOL": "红色蘑菇",
    "SNAKES & LADDERS": "蛇梯棋",
    "RAINY LADIES": "雨中女士",
    "SPACE BOY": "太空男孩",
    "THE BLACK CAT": "黑猫",
    "BLACK DINER": "黑色餐厅",
    "FLORAL BLUE MONSTER": "蓝色花怪兽",
    "MEADOW FLOWER": "草地野花",
    "RED GINGHAM": "红色格纹", "GREEN GINGHAM": "绿色格纹",
    "RED WHITE DOTS": "红白圆点",
    "BLACK BLUE DOTS": "黑蓝圆点",
    "BLACK WHITE DOTS": "黑白圆点",
    "RED SPOT": "红点", "RED SPOTTY": "红色圆点",
    "WHITE HEART": "白色爱心",
    "RED GINGHAM ROSE": "红色格纹玫瑰",
    "GREEN GINGHAM FLOWER": "绿色格纹花",
    "BLACK FLOCK": "黑色植绒",
    "IVORY TRELLIS": "象牙色格架",
    "HEART IVORY TRELLIS": "象牙色心形格架",
    "GINGHAM HEART": "格纹爱心",
    "HEART FILIGREE": "金银丝爱心",
    "WHITE FAIRY": "白色精灵",
    "FAIRY CAKES": "仙女蛋糕",
    "BLUE RUSSIAN FOLKART": "蓝色俄罗斯民间艺术",
    "ENGLISH ROSE": "英伦玫瑰",
    "FLYING DUCKS": "飞鸭",
    "WHITE CHALK STICKS": "白色粉笔",
    "ASSORTED COLOUR": "多色",
    "ASSORTED CAKES": "各式蛋糕",
    "SET OF MEADOW": "草地野花",
    "VINTAGE SNAP": "复古配对",
    "VINTAGE DESIGN": "复古设计",
    "RED WOOLLY HOTTIE": "红色羊毛热水袋",
    "SPORT PARTY": "运动派对",
    "CHARLIE AND LOLA": "查理与罗拉",
    "CHARLIE + LOLA": "查理与罗拉",
    "CHARLIE+LOLA": "查理与罗拉",
    "CHARLIE LOLA": "查理与罗拉",
    "CHARLOTTE": "夏洛特",
    "DRINK ME": "喝我",
    "RECORD FRAME 7\" SINGLE SIZE": "7寸唱片相框",
    "RING OF ROSES": "玫瑰之环",
    "KINGS CHOICE": "国王之选",
    "BANQUET": "盛宴", "EMPIRE": "帝国",
    "COUNTRY COTTAGE": "乡村小屋",
    "CHAMBRE": "卧室", "HOOK": "挂钩",
    "BICYCLE BELL": "自行车铃",
    "CORDON BARRIER": "警戒带",
    "OVERALL": "工装裤", "PINAFORE": "围裙",
    "DOLLY": "餐垫", "SNACK TRAY": "零食托盘",
    "PAISLEY PARK": "佩斯利公园",
    "PERFECTLY PRETTY": "完美漂亮",
    "VINTAGE DOILY": "复古餐垫",
    "CIGAR BOX": "雪茄盒", "GARDEN TOOLS": "园艺工具",
    "SILHOUETTE": "剪影", "GOOSE FEATHER": "鹅羽毛",
    "ROSEBUD": "玫瑰花蕾", "SILK GLASSES": "丝绸眼镜盒",
    "CROCHETED": "钩针编织", "JAPANESE": "日式",
    "CHINESE STYLE": "中式风格", "SWINGING": "摇摆",
    "PEARL EARRINGS": "珍珠耳环", "SHELL NECKLACE": "贝壳项链",
    "FROG PHONE CHARM": "青蛙手机链",
    "BERTIE": "伯特", "AMBER": "琥珀色",
    "VASE + FLOWERS": "花瓶配花",
    "WATER BOMB": "水气球",
    "PIRATE CHEST": "海盗宝箱",
    "CHILDRENS OVERALL": "儿童工装裤",
    "SKY BLUE": "天蓝", "CUTLERY": "餐具套装",
    "CAKE CASES": "蛋糕盒", "PUD": "布丁", "PUDDING": "布丁",
    "CAT FOOD": "猫粮", "DOG BOWL": "狗碗", "CAT BOWL": "猫碗",
    "CHASING BALL": "追球", "WORD": "字母积木",
    "EMILY": "艾米丽", "MARIA": "玛丽亚", "ROSIE": "罗茜",
    "FLORA": "弗洛拉", "SASSORTED": "混色",
    "CROME": "铬色", "PILL BOX": "药盒",
    "GIN AND TONIC": "金酒汤力",
    "DIET": "低糖", "RIBBONS": "丝带",
    "PERFECTLY": "完美", "PRETTY": "漂亮",
    "RED VINTAGE": "红色复古",
    "FONT": "字体", "BALL": "球", "GLASS BALL": "玻璃球",
    "CHERRY LIGHTS": "樱花灯串",
    "TRINKET": "小饰品", "MEASURING": "量具",
    "SPOONS LARGE": "大量勺", "WALL CLOCK": "挂钟",
    "DINER WALL": "餐厅墙面", "LIGHT BLUE": "浅蓝",
    "SMALL BOWL": "小碗", "PINK BOWL": "粉色碗",
    "WHITE FRAME": "白色相框", "BLOCK WORD": "积木字母",
    "ONE PERSON": "一人", "METAL SIGN": "金属标牌",
    "AREA PATROLLED": "区域巡逻",
    "BLACK FLYING": "黑色飞", "FLYING DUCKS": "飞鸭",
    "PIZZA PLATE": "披萨盘", "IN BOX": "盒装",
    "SCOTTIE DOG": "苏格兰梗犬",
    "FILIGREE DOVE": "金银丝鸽子", "DOVE LARGE": "大号鸽子",
    "BLACK FLOCK": "黑色植绒", "DOOR MAT": "门垫",
    "BUILDING BLOCK": "积木", "LOVE WORD": "爱字母积木",
    "HEART STOCKING": "心形圣诞袜",
    "PADDED MOBILE": "填充挂饰",
    "FELTCRAFT DOLL": "毛毡玩偶",
    "CERAMIC 11 PC": "陶瓷11件套",
    "ROSE STORAGE BOX": "玫瑰收纳盒",
    "PAPER CHAIN": "纸链",
    "ADVENT CALENDAR": "圣诞倒数日历",
    "FIGURES TINS": "人偶铁盒", "PARTY BAG": "派对包",
    "STICKER SET": "贴纸套装", "CAKES FRIDGE MAGNETS": "蛋糕冰箱贴",
    "WOODEN BOX": "木盒", "BATH BUILDING BLOCK": "浴室积木",
    "STACKING TINS": "叠叠罐", "MINI CASES": "迷你箱",
    "SPACEBOY": "太空男孩", "MAGIC": "魔法",
    "DROP": "耳坠", "EARRING": "耳环",
    "TILE": "瓷砖", "PHOTO": "照片",
    "ROUND CAKE": "圆形蛋糕", "ROUND TINS": "圆形铁罐",
    "SINGLE SIZE": "单曲尺寸", "7\"": '7寸',
    "INCENSE HOLDER": "香薰炉", "STICK": "棒",
    "GLASS JAR": "玻璃罐", "JAR GLASS": "玻璃罐",
    "SILVER PLATED": "镀银", "GOLD PLATED": "镀金",
    "ROSE GOLD": "玫瑰金", "GUNMETAL": "枪灰色",
    "RAINBOW": "彩虹", "IRIDESCENT": "彩虹色",
    "OPAQUE": "不透明", "TRANSPARENT": "透明",
    "FROSTED": "磨砂", "MATT": "哑光", "GLOSSY": "光泽",
    "TEXTURED": "纹理", "SMOOTH": "光滑",
    "LAYERED": "层叠", "3D": "立体",
    "WOODLAND": "森林", "Garden": "花园",
    "BOTANICAL": "植物", "HERBAL": "草本",
    "ZEST": "果皮", "SPICE": "香料",
    "BERRIES": "浆果", "FRUIT": "水果",
    "VEGETABLE": "蔬菜", "HERB": "香草",
    "SEED": "种子", "BULB": "球茎",
    "POT": "盆", "PLANTER": "花盆",
    "PLANT": "植物", "SAPLING": "树苗",
    "BRANCH": "树枝", "TWIG": "细枝",
    "BARK": "树皮", "ROOT": "根",
    "MUSHROOM": "蘑菇", "TOADSTOOL": "毒菌帽",
    "ACORN": "橡果", "CHESTNUT": "栗子",
    "WALNUT": "核桃", "ALMOND": "杏仁",
    "PECAN": "碧根果", "PISTACHIO": "开心果",
    "COCONUT": "椰子", "BANANA": "香蕉",
    "GRAPE": "葡萄", "MELON": "瓜",
    "PEACH": "桃子", "PLUM": "李子",
    "APRICOT": "杏子", "FIG": "无花果",
    "DATE": "枣", "OLIVE": "橄榄",
    "CITRUS": "柑橘", "TROPICAL": "热带",
    "EXOTIC": "异域", "NATIVE": "本土",
    "WILD": "野生", "ORGANIC": "有机",
    "NATURAL": "天然", "PURE": "纯净",
    "FRESH": "新鲜", "RIPE": "成熟",
    "RAW": "生食", "COOKED": "熟食",
    "BAKED": "烘烤", "ROASTED": "烤制",
    "GRILLED": "烧烤", "STEAMED": "蒸制",
    "BOILED": "水煮", "FRIED": "油炸",
    "SMOKED": "烟熏", "CURRY": "咖喱",
    "SAUCE": "酱料", "DRESSING": "调味汁",
    "SPREAD": "涂抹酱", "DIP": "蘸酱",
    "TOPPING": "配料", "FILLING": "馅料",
    "CRUST": "外皮", "CRUMB": "碎屑",
    "SLICE": "切片", "PORTION": "份",
    "SERVING": "上菜", "PLATING": "摆盘",
    "GARNISH": "装饰", "DECOR": "点缀",
    "FINISH": "收尾", "TOUCH": "点缀",
    "POSTAGE": "邮费", "MANUAL": "手册",
    "BANK CHARGES": "银行手续费", "SAMPLES": "样品",
    "DISCOUNT": "折扣", "ADJUSTMENT": "调整",
    "AMAZON FEE": "亚马逊费用", "CARRIAGE": "运费",
    "LUGGAGE TAG": "行李牌", "LUGGAGETAG": "行李牌",
    "DOOR HANGER": "门挂", "DOORHANGER": "门挂",
    "TOILET ROLL": "卷纸", "TOILETROLL": "卷纸",
    "POCKET BOOK": "口袋本", "POCKETBOOK": "口袋本",
    "TRAVELING FAN": "旅行扇", "TRAVELINGFAN": "旅行扇",
    "SKETCHBOOK": "素描本", "JOURNAL": "日记本",
    "CHALKBOARD": "黑板式", "TIARA": "皇冠",
    "GRASS SKIRT": "草裙", "GRASSSKIRT": "草裙",
    "SOCK PUPPET": "袜子玩偶", "SOCKPUPPET": "袜子玩偶",
    "POM-POM CURTAIN": "毛球窗帘", "POMPOMCURTAIN": "毛球窗帘",
    "CARNIVAL POUFFE": "嘉年华脚凳", "CARNIVALPOUFFE": "嘉年华脚凳",
    "CHINESE STYLE SCISSOR": "中式剪刀", "CHINESESTYLESCISSOR": "中式剪刀",
    "FISHING GNOME": "钓鱼地精", "FISHINGGNOME": "钓鱼地精",
    "SANDALWOOD FAN": "檀香扇", "SANDALWOODFAN": "檀香扇",
    "SOMBRERO": "墨西哥草帽", "COW": "奶牛",
    "SPACE OWL": "太空猫头鹰", "SPACEOWL": "太空猫头鹰",
    "SPACE FROG": "太空青蛙", "SPACEFROG": "太空青蛙",
    "DOLPHIN": "海豚", "DOLPHINS": "海豚",
    "GLOW IN THE DARK": "夜光", "GLOW·DARK": "夜光",
    "ABSTRACT CIRCLE": "抽象圆圈", "ABSTRACTCIRCLE": "抽象圆圈",
    "LIBRARY LAMP": "图书馆台灯", "LIBRARYLAMP": "图书馆台灯",
    "EDWARDIAN": "爱德华时代", "TOILET ROLL UNIT": "卷纸架",
    "TOXIC AREA": "危险区域", "MOODY BOY": "忧郁男孩",
    "VIP": "贵宾", "QUEEN OF SKIES": "天空女王",
    "ELEPHANT": "大象", "LOUVRE": "卢浮宫",
    "COLOURFUL": "多彩", "MEDIUM": "中型",
    "BANK CHARGES": "银行手续费", "BANKCHARGES": "银行手续费",
    "WALL THERMOMETER": "温度计", "WALLTHERMOMETER": "温度计",
    "PSYCHEDELIC": "迷幻", "ALPHABET STENCIL": "字母模板",
    "STENCIL CRAFT": "模板手工", "HOLIDAY FUN": "假期趣味",
    "LUDO": "飞行棋", "FRISBEE": "飞盘", "FLYING DISC": "飞盘",
    "WHEELBARROW": "手推车", "PAPERWEIGHT": "纸镇",
    "CHILDHOOD MEMORIES": "童年回忆", "KINGS CHOICE": "国王之选",
    "FUSCHIA": "紫红色", "VOILE POINTY SHOE": "纱尖头鞋",
    "TOAST RACK": "烤面包架", "TOASTRACK": "烤面包架",
    "BROCANTE COAT RACK": "复古衣架", "BROCANTECOATRACK": "复古衣架",
    "SCHOOL DESK CHAIR": "课桌椅", "SCHOOLDESKCHAIR": "课桌椅",
    "JUNGLE POPSICLE": "丛林冰棒", "ICE LOLLY MOULDS": "冰棍模具",
    "CORDIAL JUG": "果汁壶", "CORDIALJUG": "果汁壶",
    "TRELLIS COAT RACK": "格架衣架", "TRELLISCOATRACK": "格架衣架",
    "POPPY FIELD": "罂粟花田", "SHOPPING BOARD": "砧板",
    "ORBIT": "轨道", "DOILY": "餐垫", "DOLLY": "餐垫",
    "BIRDIE": "小鸟", "CRAFT": "手工品",
    "PAISLEY PARK": "佩斯利公园", "RED VINTAGE": "红色复古",
    "PERFECTLY PRETTY": "完美漂亮", "VINTAGE DOILY": "复古餐垫",
    "BICYCLE CLIPS": "自行车夹", "HAPPY FOREST": "快乐森林",
    "FOREST": "森林",
    "PANTRY KITCHEN THERMOMETER": "厨房食品温度计",
    "ZINC WIRE KITCHEN ORGANISER": "锌丝厨房收纳架",
    "ZINCWIREKITCHENORGANISER": "锌丝厨房收纳架",
}


QUANTITY_PATTERNS = [
    (re.compile(r"^SET OF (\d+) (.+)", re.I), "{1}{0}件套"),
    (re.compile(r"^SET/(\d+) (.+)", re.I), "{1}{0}件套"),
    (re.compile(r"^SET (\d+) (.+)", re.I), "{1}{0}件套"),
    (re.compile(r"^SET3 (.+)", re.I), "{0}3件套"),
    (re.compile(r"^SET 12 (.+)", re.I), "{0}12件套"),
    (re.compile(r"^SET 8 (.+)", re.I), "{0}8件套"),
    (re.compile(r"^SET 6 (.+)", re.I), "{0}6件套"),
    (re.compile(r"^SET 4 (.+)", re.I), "{0}4件套"),
    (re.compile(r"^SET 3 (.+)", re.I), "{0}3件套"),
    (re.compile(r"^SET 2 (.+)", re.I), "{0}2件套"),
    (re.compile(r"^PACK OF (\d+) (.+)", re.I), "{1}{0}件装"),
    (re.compile(r"^PACK (\d+) (.+)", re.I), "{1}{0}件装"),
    (re.compile(r"^(\d+) PACK (.+)", re.I), "{1}{0}件装"),
    (re.compile(r"^(.+) (\d+) PACK$", re.I), "{1}{0}件装"),
    (re.compile(r"^(\d+) (.+) SET$", re.I), "{0}{1}件套"),
    (re.compile(r"^(\d+) PC (.+)", re.I), "{0}{1}件套"),
    (re.compile(r"^(\d+) PIECE (.+)", re.I), "{0}{1}件套"),
]

NUMBER_WORDS = {
    "ONE": "1", "TWO": "2", "THREE": "3", "FOUR": "4", "FIVE": "5",
    "SIX": "6", "SEVEN": "7", "EIGHT": "8", "NINE": "9", "TEN": "10",
    "ELEVEN": "11", "TWELVE": "12", "TWENTY": "20", "THIRTY": "30",
    "FORTY": "40", "FIFTY": "50", "SIXTY": "60",
}

STOP_WORDS = {
    "IN", "WITH", "FOR", "AND", "THE", "A", "AN", "OF", "ON", "TO",
    "BY", "AT", "FROM", "OR", "AS", "IS", "ARE", "WAS", "WERE", "BE",
    "BEEN", "BEING", "HAVE", "HAS", "HAD", "DO", "DOES", "DID",
    "WILL", "WOULD", "SHOULD", "CAN", "COULD", "MAY", "MIGHT",
    "THIS", "THAT", "THESE", "THOSE", "IT", "ITS", "MY", "YOUR",
    "HIS", "HER", "OUR", "THEIR", "WE", "YOU", "HE", "SHE", "THEY",
    "WHAT", "WHICH", "WHO", "WHOM", "WHOSE", "WHERE", "WHEN", "WHY", "HOW",
    "NOT", "NO", "ONLY", "OWN", "SAME", "SO", "THAN", "TOO", "VERY",
    "JUST", "ABOUT", "ABOVE", "AFTER", "AGAIN", "ALL", "ALSO", "AM",
    "ANOTHER", "ANY", "BECAUSE", "BEFORE", "BELOW", "BETWEEN", "BOTH",
    "BUT", "CALL", "COME", "COULD", "DAY", "DID", "DO", "DOWN", "EACH",
    "EVEN", "EVERY", "FIND", "FIRST", "GET", "GOOD", "GREAT", "HERE",
    "HIGH", "HIM", "HIMSELF", "HIS", "HOW", "IF", "INTO", "JUST",
    "KEEP", "LAST", "LIKE", "LONG", "LOOK", "MAKE", "MANY", "MORE",
    "MOST", "MUCH", "MUST", "MY", "MYSELF", "NEW", "NOW", "OFF",
    "OLD", "ONLY", "OTHER", "OUR", "OUT", "OVER", "OWN", "PART",
    "PEOPLE", "PUT", "SAID", "SEE", "SHE", "SHOULD", "SHOW", "SIDE",
    "SMALL", "SOME", "SOUND", "STILL", "SUCH", "TAKE", "THAN", "THAT",
    "THE", "THEM", "THEN", "THEIR", "THEY", "THING", "THINK", "THIS",
    "THOSE", "THOUGH", "THREE", "THROUGH", "TIME", "TOO", "UNDER",
    "UNTIL", "UP", "USE", "VERY", "WANT", "WAY", "WELL", "WERE",
    "WHAT", "WHERE", "WHICH", "WHILE", "WHO", "WILL", "WITH", "WORDS",
    "WORK", "WORLD", "WOULD", "WRITE", "YEAR", "YOU", "YOUR", "YOURS",
}


def _apply_dict(text, d, case_sensitive=False):
    result = text
    for eng, cn in sorted(d.items(), key=lambda x: -len(x[0])):
        flags = 0 if case_sensitive else re.IGNORECASE
        result = re.sub(re.escape(eng), cn, result, flags=flags)
    return result


def translate_product_name(name):
    if not name or len(name.strip()) < 2:
        return name

    original = name.strip()
    result = original

    result = result.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
    result = result.replace("&quot;", '"').replace("&#39;", "'")

    for eng, digit in sorted(NUMBER_WORDS.items(), key=lambda x: -len(x[0])):
        result = re.sub(r"\b" + re.escape(eng) + r"\b", digit, result, flags=re.I)

    for pattern, template in QUANTITY_PATTERNS:
        m = pattern.match(result)
        if m:
            groups = m.groups()
            ng = len(groups)
            if ng == 2:
                result = template.format(groups[1], groups[0])
            elif ng == 1:
                result = template.format(groups[0])
            else:
                result = template
            result = result.strip()
            break

    result = _apply_dict(result, PRODUCTS_CORE)

    result = _apply_dict(result, STYLES)

    result = _apply_dict(result, MATERIALS)

    result = _apply_dict(result, COLORS)

    for sw in STOP_WORDS:
        result = re.sub(r"\b" + re.escape(sw) + r"\b", "", result, flags=re.I)

    result = re.sub(r"\s+", "", result)
    result = result.replace("&", "·")
    result = result.replace("+", "·")
    result = result.replace("/", "·")
    result = result.replace(",", "·")
    result = result.replace("-", "")
    result = result.replace("'", "")
    result = re.sub(r"[A-Za-z]{2,}", "", result)
    result = re.sub(r"[A-Za-z]", "", result)
    result = re.sub(r"·+", "·", result).strip("·")

    return result if result else original